import { ScryfallCardImageUris } from "./scryfall-card-image-uris.model"
import { ScryfallCardLegalities } from "./scryfall-card-legalities.model"
import { ScryfallCardPrices } from "./scryfall-card-prices.model"
import { ScryfallCardPurchaseUris } from "./scryfall-card-purchase-uris.model"
import { ScryfallCardRelatedUris } from "./scyrfall-card-related-uris.model"

export class ScryfallCard {
    constructor(
        public object: string,
        public id: string,
        public oracle_id: string,
        public multiverse_ids: string[],
        public mtgo_id: string,
        public tcgplayer_etched_id: string,
        public cardmarket_id: string,
        public name: string,
        public lang: string,
        public released_at: string,
        public uri: string,
        public uscryfall_uri: string,
        public layout: string,
        public highres_image: boolean,
        public image_uris: ScryfallCardImageUris,
        public mana_cost: string,
        public cmc: string,
        public type_line: string,
        public oracle_text: string,
        public power: string,
        public toughness: string,
        public colors: string[],
        public color_identity: string[],
        public keywords: string[],
        public legalities: ScryfallCardLegalities,
        public games: string[],
        public reserved: boolean,
        public foil: boolean,
        public nonfoil: boolean,
        public finishes: string[],
        public oversized: boolean,
        public promo: boolean,
        public reprint: boolean,
        public variation: boolean,
        public set_id: string,
        public set: string,
        public set_name: string,
        public set_type: string,
        public set_uri: string,
        public set_search_uri: string,
        public scryfall_set_uri: string,
        public rulings_uri: string,
        public prints_search_uri: string,
        public collector_number: string,
        public digital: boolean,
        public rarity: string,
        public card_back_id: string,
        public artist: string,
        public artist_ids: string[],
        public illustration_id: string,
        public border_color: string,
        public frame: string,
        public frame_effects: string[],
        public security_stamp: string,
        public full_art: boolean,
        public textless: boolean,
        public booster: boolean,
        public story_spotlight: boolean,
        public promo_types: string[],
        public edhrec_rank: string,
        public prices: ScryfallCardPrices,
        public related_uris: ScryfallCardRelatedUris,
        public purchase_uris: ScryfallCardPurchaseUris,
        public tcgplayer_id: string,
        public faces: ScryfallCardImageUris[],
    ) {}

    static fromJSON(json: any): ScryfallCard {
        const images = ScryfallCardImageUris.fromJSON(json.image_uris)
        const legalities = ScryfallCardLegalities.fromJSON(json.legalities)
        const prices = ScryfallCardPrices.fromJSON(json.prices)
        const relatedUris = ScryfallCardRelatedUris.fromJSON(json.related_uris)
        const purchaseUris = ScryfallCardPurchaseUris.fromJSON(json.purchase_uris)
        const faces = json.card_faces ? json.card_faces.map((faceData: any) => ScryfallCardImageUris.fromJSON(faceData.image_uris)) : []

        return new ScryfallCard(
            json?.object,
            json?.id,
            json?.oracle_id,
            json?.multiverse_ids,
            json?.mtgo_id,
            json?.tcgplayer_etched_id,
            json?.cardmarket_id,
            json?.name,
            json?.lang,
            json?.released_at,
            json?.uri,
            json?.uscryfall_uri,
            json?.layout,
            json?.highres_image,
            images,
            json?.mana_cost,
            json?.cmc,
            json?.type_line,
            json?.oracle_text,
            json?.power,
            json?.toughness,
            json?.colors,
            json?.color_identity,
            json?.keywords,
            legalities,
            json?.games,
            json?.reserved,
            json?.foil,
            json?.nonfoil,
            json?.finishes,
            json?.oversized,
            json?.promo,
            json?.reprint,
            json?.variation,
            json?.set_id,
            json?.set,
            json?.set_name,
            json?.set_type,
            json?.set_uri,
            json?.set_search_uri,
            json?.scryfall_set_uri,
            json?.rulings_uri,
            json?.prints_search_uri,
            json?.collector_number,
            json?.digital,
            json?.rarity,
            json?.card_back_id,
            json?.artist,
            json?.artist_ids,
            json?.illustration_id,
            json?.border_color,
            json?.frame,
            json?.frame_effects,
            json?.security_stamp,
            json?.full_art,
            json?.textless,
            json?.booster,
            json?.story_spotlight,
            json?.promo_types,
            json?.edhrec_rank,
            prices,
            relatedUris,
            purchaseUris,
            json?.tcgplayer_id,
            faces,
        )
    }
}