import { ScryfallCardImageUris } from "./scryfall-card-image-uris.model"
import { ScryfallCardLegalities } from "./scryfall-card-legalities.model"
import { ScryfallCardPrices } from "./scryfall-card-prices.model"
import { ScryfallCardPurchaseUris } from "./scryfall-card-purchase-uris.model"
import { ScryfallCardRelatedUris } from "./scyrfall-card-related-uris.model"

export class ScryfallCard {
    constructor(
        public object: string,
        public id: string,
        public oracle_id: string,
        public multiverse_ids: string[],
        public mtgo_id: string,
        public tcgplayer_etched_id: string,
        public cardmarket_id: string,
        public name: string,
        public lang: string,
        public released_at: string,
        public uri: string,
        public uscryfall_uri: string,
        public layout: string,
        public highres_image: boolean,
        public image_uris: ScryfallCardImageUris,
        public mana_cost: string,
        public cmc: string,
        public type_line: string,
        public oracle_text: string,
        public power: string,
        public toughness: string,
        public colors: string[],
        public color_identity: string[],
        public keywords: string[],
        public legalities: ScryfallCardLegalities,
        public games: string[],
        public reserved: boolean,
        public foil: boolean,
        public nonfoil: boolean,
        public finishes: string[],
        public oversized: boolean,
        public promo: boolean,
        public reprint: boolean,
        public variation: boolean,
        public set_id: string,
        public set: string,
        public set_name: string,
        public set_type: string,
        public set_uri: string,
        public set_search_uri: string,
        public scryfall_set_uri: string,
        public rulings_uri: string,
        public prints_search_uri: string,
        public collector_number: string,
        public digital: boolean,
        public rarity: string,
        public card_back_id: string,
        public artist: string,
        public artist_ids: string[],
        public illustration_id: string,
        public border_color: string,
        public frame: string,
        public frame_effects: string[],
        public security_stamp: string,
        public full_art: boolean,
        public textless: boolean,
        public booster: boolean,
        public story_spotlight: boolean,
        public promo_types: string[],
        public edhrec_rank: string,
        public prices: ScryfallCardPrices,
        public related_uris: ScryfallCardRelatedUris,
        public purchase_uris: ScryfallCardPurchaseUris,
        public tcgplayer_id: string,
        public faces: ScryfallCardImageUris[],
    ) {}

    static fromObject(obj: any): ScryfallCard {
        const images = ScryfallCardImageUris.fromObject(obj.image_uris)
        const legalities = ScryfallCardLegalities.fromObject(obj.legalities)
        const prices = ScryfallCardPrices.fromObject(obj.prices)
        const relatedUris = ScryfallCardRelatedUris.fromObject(obj.related_uris)
        const purchaseUris = ScryfallCardPurchaseUris.fromObject(obj.purchase_uris)

        // Ligne problématique, conversion d'un objet scryfallCard en imageUris directement
        const faces = obj.card_faces ? obj.card_faces.map((faceData: any) => ScryfallCardImageUris.fromObject(faceData.image_uris)) : []

        return new ScryfallCard(
            obj?.object,
            obj?.id,
            obj?.oracle_id,
            obj?.multiverse_ids,
            obj?.mtgo_id,
            obj?.tcgplayer_etched_id,
            obj?.cardmarket_id,
            obj?.name,
            obj?.lang,
            obj?.released_at,
            obj?.uri,
            obj?.uscryfall_uri,
            obj?.layout,
            obj?.highres_image,
            images,
            obj?.mana_cost,
            obj?.cmc,
            obj?.type_line,
            obj?.oracle_text,
            obj?.power,
            obj?.toughness,
            obj?.colors,
            obj?.color_identity,
            obj?.keywords,
            legalities,
            obj?.games,
            obj?.reserved,
            obj?.foil,
            obj?.nonfoil,
            obj?.finishes,
            obj?.oversized,
            obj?.promo,
            obj?.reprint,
            obj?.variation,
            obj?.set_id,
            obj?.set,
            obj?.set_name,
            obj?.set_type,
            obj?.set_uri,
            obj?.set_search_uri,
            obj?.scryfall_set_uri,
            obj?.rulings_uri,
            obj?.prints_search_uri,
            obj?.collector_number,
            obj?.digital,
            obj?.rarity,
            obj?.card_back_id,
            obj?.artist,
            obj?.artist_ids,
            obj?.illustration_id,
            obj?.border_color,
            obj?.frame,
            obj?.frame_effects,
            obj?.security_stamp,
            obj?.full_art,
            obj?.textless,
            obj?.booster,
            obj?.story_spotlight,
            obj?.promo_types,
            obj?.edhrec_rank,
            prices,
            relatedUris,
            purchaseUris,
            obj?.tcgplayer_id,
            faces,
        )
    }
}